project:
  type: website
  output-dir: docs

website:
  title: "Kaija Gahm"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  page-footer:
    background: light # or dark
    left:
      - "Copyright 2024, Kaija Gahm"
    right:
      - icon: github
        href: https://github.com/kaijagahm

format:
  html:
    theme:
      - mystyle.scss
    mainfont: Urbanist
    toc: true
    page-layout: full
  