---
title: "Publications"
nocite: |
  @*
engine: knitr
---

```{css}
#| echo: false

.publication {
  margin-bottom: 1.5em;
  padding-left: 2em;
  text-indent: -2em;
}

.publication p {
  margin: 0;
  display: inline;
}

.publication p::after {
  content: "\A";
  white-space: pre;
}
```

::: {.publication}
**Gahm, K.**, Acácio, M., Anglister, N., Vaadia, G., Spiegel, O., & Pinter-Wollman, N. (In press). Relationship between spatial and social phenotypes in an avian scavenger. Journal of Animal Ecology. <https://doi.org/10.1111/1365-2656.70316>
:::

::: {.publication}
**Gahm, K.**, D'Bastiani, E., Anglister, N., Vaadia, G., Acácio, M., Spiegel, O., & Pinter-Wollman, N. (2026). Selection of timescales to study social network temporal dynamics in vultures. Animal Behaviour, 232, 123442. <https://doi.org/10.1016/j.anbehav.2025.123442>

<a href="publications/Gahm et al.-2026-Selection of timescales to study social network te.pdf" download>**Download PDF**</a>

![Figure 3. Multilayer reducibility curves at different aggregation window sizes. Feeding (yellow) and flight (blue) social networks for the postbreeding season in 2023. Each panel
shows a different timescale: (a) 1 day, (b) 5 days, (c) 10 days and (d) 25 days. The Y axis shows the Von Neumann relative entropy of the current reduced multilayer network
compared to the fully aggregated network, normalized to the maximum value for each curve; the X axis shows how many layers have been aggregated. The dotted black line
represents the hypothetical linear decrease in entropy that is expected if each layer contributed exactly the same amount of information.](images/timescales_reflist_fig.png){fig-alt="Figure from the publication, showing multilayer aggregation results for flight and feeding networks."}

:::

::: {.publication}
**Gahm, K.**, Spiegel, O., & Pinter-Wollman, N. (2026). How are social preferences realized? Considering the importance of space: A comment on De Moor et al. (2025). Behavioral Ecology, arag065. <https://doi.org/10.1093/beheco/arag065>

<a href="publications/Gahm et al.-2026-How are social preferences realized Considering t.pdf" download>**Download PDF**</a>
:::

::: {.publication}
Russo, N. J., **Gahm, K.**, Zuercher, M. E., Hernandez, K., Blakey, R. V., Niesner, C., & Abelson, E. (2026). Monitoring animal movement diversity as a component of biodiversity. Frontiers in Ecology and the Environment, e70038. <https://doi.org/10.1002/fee.70038>

<a href="publications/Russo et al.-Monitoring animal movement diversity as a componen.pdf" download>**Download PDF**</a>

![Figure 1. A framework for metrics that can be used to quantify animal movement diversity, from the level of an individual animal to a community, with
example visualizations and research questions.](images/movementdiversity_reflist_fig.png.png){fig-alt="Figure from the publication, showing a conceptual representation of movement diversity at different scales."}
:::

::: {.publication}
Amin, N., Barnes, K., Crall, A., **Gahm, K.**, Newman, S., Sutton-Kennedy, T., & Word, K. (2026). Community Organizing for STEM Professionals. QUBES Educational Resources. <https://doi.org/10.25334/VWRN-8M23>

<a href="publications/CommunityOrganizingHandbookForSTEMProfessionals-citation-29645.pdf" download>**Download PDF**</a>
:::

::: {.publication}
Acácio, M., **Gahm, K.**, Anglister, N., Vaadia, G., Hatzofe, O., Harel, R., Efrat, R., Nathan, R., Pinter-Wollman, N., & Spiegel, O. (2024). Behavioral plasticity shapes population aging patterns in a long-lived avian scavenger. Proceedings of the National Academy of Sciences, 121(35), e2407298121. <https://doi.org/10.1073/pnas.2407298121>

<a href="publications/Acácio et al.-2024-Behavioral plasticity shapes population aging patt.pdf" download>**Download PDF**</a>

![Fig. 3. Age-related
changes in movement and social behavior of griffon vultures. Each panel A–F represents the model predictions, backtransformed to the
original data scale, and the 95% CI for the effect of age on movement (A–C) and social behaviors (D–F): (A) probability of remaining at the same roost-site on consecutive nights (roost fidelity)](images/vultureage_reflist_fig.png){fig-alt="Figure from the publication, showing a nonlinear positive relationship between vulture age and probability of roost fidelity."}
:::

::: {.publication}
D'Bastiani, E., Anglister, N., Lysnyansky, I., Mikula, I., Acácio, M., Vaadia, G., **Gahm, K.**, Spiegel, O., & Pinter-Wollman, N. (2024). Social interactions do not affect mycoplasma infection in griffon vultures. Royal Society Open Science, 11(12), 240500. <https://doi.org/10.1098/rsos.240500>

<a href="publications/D'Bastiani et al.-Social interactions do not affect mycoplasma infec.pdf" download>**Download PDF**</a>
:::

::: {.publication}
**Gahm, K.**, Nguyen, R., Acácio, M., Anglister, N., Vaadia, G., Spiegel, O., & Pinter-Wollman, N. (2024). A wrap-around movement path randomization method to distinguish social and spatial drivers of animal interactions. Philosophical Transactions of the Royal Society B: Biological Sciences, 379(1912), 20220531. <https://doi.org/10.1098/rstb.2022.0531>

<a href="publications/Gahm et al.-2024-A wrap-around movement path randomization method t.pdf" download>**Download PDF**</a>
:::

::: {.publication}
Van Appledorn, M., Jankowski, K., **Gahm, K.**, Budd, S., Baumann, D., Bennie, B., Erickson, R., Haro, R., & Rohweder, J. (2024). The where and why of large wood occurrence in the Upper Mississippi and Illinois Rivers. Earth Surface Processes and Landforms, n/a(n/a). <https://doi.org/10.1002/esp.5911>

<a href="publications/Van Appledorn et al.-2024-The where and why of large wood occurrence in the.pdf" download>**Download PDF**</a>
:::

::: {.publication}
Venable, G. X., **Gahm, K.**, & Prum, R. O. (2022). Hummingbird plumage color diversity exceeds the known gamut of all other birds. Communications Biology, 5(1), Article 1. <https://doi.org/10.1038/s42003-022-03518-2>

<a href="publications/Venable et al.-2022-Hummingbird plumage color diversity exceeds the kn.pdf" download>**Download PDF**</a>
:::

::: {.publication}
Bishop, C. E., **Gahm, K.**, Hendry, A. P., Jones, S. E., Stange, M., & Solomon, C. T. (2022). Benthic–limnetic morphological variation in fishes: Dissolved organic carbon concentration produces unexpected patterns. Ecosphere, 13(3), e3965. <https://doi.org/10.1002/ecs2.3965>

<a href="publications/Bishop et al.-2022-Benthic–limnetic morphological variation in fishes.pdf" download>**Download PDF**</a>
:::

::: {.publication}
**Gahm, K.**, Arietta, A. Z. A., & Skelly, D. K. (2021). Temperature-mediated trade-off between development and performance in larval wood frogs (Rana sylvatica). Journal of Experimental Zoology Part A: Ecological and Integrative Physiology, 335(1), 146–157. <https://doi.org/10.1002/jez.2434>

<a href="publications/Gahm et al.-2021-Temperature-mediated trade-off between development.pdf" download>**Download PDF**</a>

![FIGURE 3 Relationship between development rate and burst speed for (a) lab tadpoles and (b) wild tadpoles. Dots represent pond‐wise
means, and in (a), lines connect means from the same pond. Marginal density plots are based on individual tadpoles rather than pond‐wise
means. Orange and blue represent tadpoles reared in the high‐ and low‐temperature incubators, respectively [Color figure can be viewed at
wileyonlinelibrary.com]](images/burstspeed_reflist_fig.png){fig-alt="Figure from the publication, showing a negative relationship between burst speed and developmental rate."}
:::
